In [1]:
import numpy as np
import re

In [2]:
tempLines = np.load("tempData.npy")

In [3]:
print(tempLines)
np.info(tempLines)

['GRID           1       0398.0063111.0105-.360-15       0               0        \n'
 'GRID           2       0288.833316.5890351.40000       0               0        \n'
 'GRID           3       0392.888659.97629.2062-08       0               0        \n'
 ...
 'GRID      271489       014.7348153.8218646.17890       0               0        \n'
 'GRID      271490       0224.702118.4115978.74021       0               0        \n'
 'GRID      271491       0258.358918.39150-75.1739       0               0        \n']
class:  ndarray
shape:  (271491,)
strides:  (324,)
itemsize:  324
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x160000000
byteorder:  little
byteswap:  False
type: <U81


In [4]:
tempLines=np.core.defchararray.replace(tempLines,"\n",'', count=None)

In [5]:
#import textwrap
#width = 8
#tempLinesSlow = np.array([[substring for substring in textwrap.wrap(string, width)] for string in tempLines])
#print(tempLinesSlow)

In [6]:
width=8
NOC=int(np.dtype(tempLines.dtype).itemsize/4)
if (NOC % width) == 0:
    pass
else:
    print(f"problems")
arraySize=[np.size(tempLines),int(NOC/width)]

In [7]:
tempLines=np.array([string[i:i+width] for string in tempLines for i in range(0, len(string), width)], dtype='U8')
tempLines=np.reshape(tempLines,arraySize)

In [31]:
tempGrid=tempLines[:,[3,4,5]]
#tempGrid=tempGrid.astype(float)
#tempGrid=np.core.defchararray.replace(tempGrid,"+",'e+', count=None)
#tempGrid=np.core.defchararray.replace(tempGrid,"-",'e-', count=None)
tempGrid = np.core.defchararray.replace(tempGrid, '-', 'e-')
tempGrid = np.core.defchararray.replace(tempGrid, '+', 'e+')

#tempGrid = np.array([i.lstrip("e") if i.startswith("e") else i for i in tempGrid ])

remove_e = lambda x: x if x[0]!='e' else x[1:]
remove_e = np.vectorize(remove_e)
tempGrid = remove_e(tempGrid)

tempGrid=tempGrid.astype(float)
print(tempGrid)



[[ 3.980063e+02  1.110105e+02 -3.600000e-16]
 [ 2.888333e+02  1.658903e+01  5.140000e+01]
 [ 3.928886e+02  5.997629e+01  2.062000e-09]
 ...
 [ 1.473481e+01  5.382186e+01  4.617890e+01]
 [ 2.247021e+02  1.841159e+01  7.874021e+01]
 [ 2.583589e+02  1.839150e+01 -7.517390e+01]]


In [28]:
import numpy as np

# Create a numpy array
arr = np.array(['-5.75e-3', '4.5e-2', '6.2e-1'])

#remove 'e' from string starting with 'e' using numpy.core.defchararray.replace()
arr = np.core.defchararray.replace(arr, 'e', '', where=lambda x: x.startswith('e'))

print(arr)

TypeError: replace() got an unexpected keyword argument 'where'